---
- name: yum update
  yum: name=* state=latest
  become: yes

- name: add rbenv initialization to profile system-wide
  template: src=rbenv_system.sh.j2 dest=/etc/profile.d/rbenv.sh owner=root group=root mode=0755
  become: yes

- name: check rbenv installed
  stat: path={{ rbenv_root }}
  register: rbenv
- name: git clone rbenv
  git: repo=https://github.com/rbenv/rbenv.git dest={{ rbenv_root }}
  when: not rbenv.stat.exists
  become: yes
- name: check ruby_build installed
  stat: path={{ rbenv_root }}/plugins/ruby-build
  register: ruby_build
- name: git clone ruby_build
  git: repo=https://github.com/rbenv/ruby-build.git dest={{ rbenv_root }}/plugins/ruby-build
  when: not ruby_build.stat.exists
  become: yes
- name: update rbenv
  command: git pull --rebase chdir={{ rbenv_root }}
  become: yes
- name: update ruby-build
  command: git pull --rebase chdir={{ rbenv_root }}/plugins/ruby-build
  become: yes
- name: install ruby dependencies
  yum: name={{item}} state=latest
  become: yes
  with_items:
    - gcc
    - make
    - openssl
    - openssl-devel
    - gcc-c++
    - mysql-devel
    - readline-devel
    - sqlite-devel

- name: check ruby installed
  shell: /bin/bash -lc "rbenv versions | grep {{ruby.version}}"
  register: ruby_installed
  ignore_errors: yes
  become: yes
- name: install ruby
  shell: /bin/bash -lc "rbenv install -v {{ruby.version}} && rbenv rehash && rbenv global {{ruby.version}}"
  become: yes
  when: ruby_installed.rc != 0
- name: gem install bundler
  gem: name=bundler executable={{ rbenv_root }}/shims/gem user_install=False
  become: yes
- name: gem install rails
  gem: name=rails executable={{ rbenv_root }}/shims/gem user_install=False
  become: yes

- name: check node js installed
  shell: which node
  register: node_installed
  become: no
  failed_when: node_installed not in [0, 1]
- name: install node script
  shell: /bin/bash -lc "curl -sL https://rpm.nodesource.com/setup_8.x | bash -"
  become: yes
  when: node_installed.rc == 1
- name: install nodejs
  yum: name=nodejs state=latest
  become: yes
  when: node_installed.rc == 1
- name: install npm
  yum: name=npm state=latest
  become: yes
  when: node_installed.rc == 1
