---
# file: roles/common/tasks/main.yml
- name: set locale
  shell: localectl set-locale LANG=ja_JP.utf8
  when: ansible_env.LANG | default('') != 'ja_JP.utf8'
- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: yum update
  yum: name=* state=latest
  become: yes

- name: add bachrc alias
  lineinfile: >
    dest={{ ansible_env.HOME }}/.bashrc
    state=present
    insertafter='# User specific aliases and functions'
    line="alias vi='vim'"

- name: install vim
  yum: name=vim state=latest
  become: yes
- name: install tmux
  yum: name=tmux state=latest
  become: yes
